using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using FrameSyncMoba.RuntimeConfig;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

namespace FrameSyncMoba.EditorTools.Addressables
{
    public static class UnitPrefabAddressablesMigration
    {
        private const string LegacyRoot = "Assets/Resources/Prefab/Unit";
        private const string ArchiveRoot = "Assets/Archive/LegacyMonolithicUnitPrefabs";
        private const string LogicRoot = "Assets/Config/Formal/Prefabs/Logic/Unit";
        private const string ViewRoot = "Assets/ClientContent/Views/Unit";
        private const string PrefabTablePath = "Assets/Config/Formal/GlobalPrefabTable.asset";
        private const string CompositionReport =
            "Docs/Implementation/Addressables/UNIT_PREFAB_COMPOSITION_BASELINE.md";
        private const string MigrationReport =
            "Docs/Implementation/Addressables/UNIT_PREFAB_MIGRATION.md";

        private static readonly UnitMigrationSpec[] Specs =
        {
            new UnitMigrationSpec(1101, "VarusRuntime.prefab"),
            new UnitMigrationSpec(1102, "AatroxHeroRuntime.prefab"),
            new UnitMigrationSpec(1201, "TestMeleeMinionBlueRuntime.prefab"),
            new UnitMigrationSpec(1202, "TestMeleeMinionRedRuntime.prefab"),
            new UnitMigrationSpec(1211, "TestCasterMinionBlueRuntime.prefab"),
            new UnitMigrationSpec(1212, "TestCasterMinionRedRuntime.prefab"),
            new UnitMigrationSpec(1301, "TestTowerBlueRuntime.prefab"),
            new UnitMigrationSpec(1302, "TestTowerRedRuntime.prefab"),
        };

        private static readonly HashSet<string> LogicAssemblies =
            new HashSet<string>(StringComparer.Ordinal)
            {
                "FrameSyncMoba.Unit",
                "FrameSyncMoba.Physics",
                "FrameSyncMoba.Deterministic",
                "FrameSyncMoba.RuntimeConfig",
            };

        private static readonly HashSet<string> PresentationAssemblies =
            new HashSet<string>(StringComparer.Ordinal)
            {
                "FrameSyncMoba.FrameSync",
                "FrameSyncMoba.Bootstrap",
                "FrameSyncMoba.PlayerInput",
                "FrameSyncMoba.LuaBridge",
            };

        [MenuItem("FrameSyncMoba/Addressables/Report Legacy Unit Prefab Composition")]
        public static void GenerateCompositionReport()
        {
            Directory.CreateDirectory(Path.GetDirectoryName(CompositionReport));
            var builder = new StringBuilder();
            builder.AppendLine("# Legacy unit prefab composition baseline");
            builder.AppendLine();
            builder.AppendLine("Generated by targeted `PrefabUtility.LoadPrefabContents` traversal. Only GameObjects with non-Transform components are listed; no serialized-field reflection scan is used.");
            builder.AppendLine();

            for (int i = 0; i < Specs.Length; i++)
            {
                UnitMigrationSpec spec = Specs[i];
                string path = ResolveExistingSourcePath(spec);
                builder.AppendLine($"## {spec.PrefabId} — {spec.FileName}");
                builder.AppendLine();
                builder.AppendLine($"Source: `{path}`");
                builder.AppendLine();
                GameObject root = PrefabUtility.LoadPrefabContents(path);
                try
                {
                    Transform[] transforms = root.GetComponentsInChildren<Transform>(true);
                    for (int transformIndex = 0;
                         transformIndex < transforms.Length;
                         transformIndex++)
                    {
                        Component[] components =
                            transforms[transformIndex].GetComponents<Component>();
                        string[] names = components
                            .Where(component => component != null && !(component is Transform))
                            .Select(component => component.GetType().FullName)
                            .OrderBy(name => name, StringComparer.Ordinal)
                            .ToArray();
                        if (names.Length == 0)
                            continue;
                        builder.AppendLine(
                            $"- `{GetRelativePath(root.transform, transforms[transformIndex])}`: {string.Join(", ", names)}");
                    }
                }
                finally
                {
                    PrefabUtility.UnloadPrefabContents(root);
                }
                builder.AppendLine();
            }

            File.WriteAllText(
                CompositionReport,
                builder.ToString(),
                new UTF8Encoding(false));
            AssetDatabase.Refresh();
            Debug.Log($"[AddressablesMigration] Wrote {CompositionReport}.");
        }

        [MenuItem("FrameSyncMoba/Addressables/Migrate All Unit Logic and Views")]
        public static void MigrateAll()
        {
            EnsureFolder(ArchiveRoot);
            EnsureFolder(LogicRoot);
            EnsureFolder(ViewRoot);
            AddressableAssetSettings settings =
                AddressableAssetSettingsDefaultObject.Settings;
            if (settings == null)
                throw new InvalidOperationException("Addressables settings are required before unit migration.");
            AddressableAssetGroup unitViews =
                LocalAddressablesConfigurator.EnsureLocalGroup(
                    settings,
                    AddressablesProjectConstants.UnitViewsGroup);

            var results = new List<UnitMigrationResult>(Specs.Length);
            for (int i = 0; i < Specs.Length; i++)
                results.Add(MigrateOne(Specs[i], settings, unitViews));

            UpdateGlobalPrefabTable(results);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            WriteMigrationReport(results);
            Debug.Log(
                $"[AddressablesMigration] Migrated {results.Count} Unit prefabs into synchronous logic prefabs and local Addressable client views.");
        }

        private static UnitMigrationResult MigrateOne(
            UnitMigrationSpec spec,
            AddressableAssetSettings settings,
            AddressableAssetGroup unitViews)
        {
            string legacyPath = $"{LegacyRoot}/{spec.FileName}";
            string archivePath = $"{ArchiveRoot}/{spec.FileName}";
            string logicPath = $"{LogicRoot}/{spec.FileName}";
            string viewPath = $"{ViewRoot}/{Path.GetFileNameWithoutExtension(spec.FileName)}View.prefab";

            if (AssetDatabase.LoadAssetAtPath<GameObject>(archivePath) == null)
            {
                string archiveSource =
                    AssetDatabase.LoadAssetAtPath<GameObject>(legacyPath) != null
                        ? legacyPath
                        : logicPath;
                RequireCopy(archiveSource, archivePath);
            }

            if (AssetDatabase.LoadAssetAtPath<GameObject>(viewPath) == null)
                RequireCopy(archivePath, viewPath);

            if (AssetDatabase.LoadAssetAtPath<GameObject>(logicPath) == null)
            {
                if (AssetDatabase.LoadAssetAtPath<GameObject>(legacyPath) == null)
                    throw new InvalidOperationException(
                        $"Neither legacy nor logic prefab exists for {spec.FileName}.");
                string moveError = AssetDatabase.MoveAsset(legacyPath, logicPath);
                if (!string.IsNullOrEmpty(moveError))
                    throw new InvalidOperationException(
                        $"Could not move '{legacyPath}' to '{logicPath}': {moveError}");
            }

            StripLogicPrefab(logicPath);
            StripViewPrefab(viewPath);

            string viewGuid = AssetDatabase.AssetPathToGUID(viewPath);
            AddressableAssetEntry addressableEntry =
                settings.CreateOrMoveEntry(viewGuid, unitViews, false, false);
            string address = $"view/unit/{spec.PrefabId}";
            addressableEntry.SetAddress(address, false);
            addressableEntry.SetLabel("client-unit-view", true, false, false);

            return new UnitMigrationResult(
                spec,
                archivePath,
                logicPath,
                viewPath,
                address,
                AssetDatabase.AssetPathToGUID(logicPath),
                viewGuid);
        }

        private static void StripLogicPrefab(string path)
        {
            GameObject root = PrefabUtility.LoadPrefabContents(path);
            try
            {
                DeleteImmediateChildrenWithoutOwnership(root, ContainsLogicComponent);
                Component[] components = root.GetComponentsInChildren<Component>(true);
                for (int i = components.Length - 1; i >= 0; i--)
                {
                    Component component = components[i];
                    if (component == null || component is Transform)
                        continue;
                    if (IsPresentationComponent(component))
                        UnityEngine.Object.DestroyImmediate(component, true);
                }
                PrefabUtility.SaveAsPrefabAsset(root, path);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static void StripViewPrefab(string path)
        {
            GameObject root = PrefabUtility.LoadPrefabContents(path);
            try
            {
                DeleteImmediateChildrenWithoutOwnership(root, ContainsPresentationComponent);
                Component[] components = root.GetComponentsInChildren<Component>(true);
                for (int i = components.Length - 1; i >= 0; i--)
                {
                    Component component = components[i];
                    if (component == null || component is Transform)
                        continue;
                    if (IsLogicComponent(component))
                        UnityEngine.Object.DestroyImmediate(component, true);
                }
                PrefabUtility.SaveAsPrefabAsset(root, path);
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(root);
            }
        }

        private static void DeleteImmediateChildrenWithoutOwnership(
            GameObject root,
            Func<Transform, bool> ownsSubtree)
        {
            var delete = new List<GameObject>();
            for (int i = 0; i < root.transform.childCount; i++)
            {
                Transform child = root.transform.GetChild(i);
                if (!ownsSubtree(child))
                    delete.Add(child.gameObject);
            }
            for (int i = 0; i < delete.Count; i++)
                UnityEngine.Object.DestroyImmediate(delete[i], true);
        }

        private static bool ContainsLogicComponent(Transform root)
        {
            Component[] components = root.GetComponentsInChildren<Component>(true);
            for (int i = 0; i < components.Length; i++)
                if (components[i] != null && IsLogicComponent(components[i]))
                    return true;
            return false;
        }

        private static bool ContainsPresentationComponent(Transform root)
        {
            Component[] components = root.GetComponentsInChildren<Component>(true);
            for (int i = 0; i < components.Length; i++)
                if (components[i] != null && IsPresentationComponent(components[i]))
                    return true;
            return false;
        }

        private static bool IsLogicComponent(Component component)
        {
            if (component is Collider ||
                component is Rigidbody ||
                component is CharacterController)
                return true;
            string assembly = component.GetType().Assembly.GetName().Name;
            return LogicAssemblies.Contains(assembly);
        }

        private static bool IsPresentationComponent(Component component)
        {
            if (component is Animator ||
                component is Renderer ||
                component is MeshFilter ||
                component is ParticleSystem ||
                component is AudioSource ||
                component is AudioListener ||
                component is Light ||
                component is LODGroup)
                return true;
            string assembly = component.GetType().Assembly.GetName().Name;
            return PresentationAssemblies.Contains(assembly);
        }

        private static void UpdateGlobalPrefabTable(
            IReadOnlyList<UnitMigrationResult> results)
        {
            GlobalPrefabTable table =
                AssetDatabase.LoadAssetAtPath<GlobalPrefabTable>(PrefabTablePath);
            if (table == null)
                throw new InvalidOperationException(
                    $"Missing GlobalPrefabTable at '{PrefabTablePath}'.");

            var byId = results.ToDictionary(result => result.Spec.PrefabId);
            var serialized = new SerializedObject(table);
            SerializedProperty groups = serialized.FindProperty("prefabGroups");
            for (int groupIndex = 0;
                 groupIndex < groups.arraySize;
                 groupIndex++)
            {
                SerializedProperty group = groups.GetArrayElementAtIndex(groupIndex);
                if (group.FindPropertyRelative("kind").intValue != (int)PrefabKind.Unit)
                    continue;
                SerializedProperty entries = group.FindPropertyRelative("entries");
                for (int entryIndex = 0;
                     entryIndex < entries.arraySize;
                     entryIndex++)
                {
                    SerializedProperty entry = entries.GetArrayElementAtIndex(entryIndex);
                    int prefabId = entry.FindPropertyRelative("prefabId").intValue;
                    if (!byId.TryGetValue(prefabId, out UnitMigrationResult result))
                        continue;
                    entry.FindPropertyRelative("unityPrefab").objectReferenceValue =
                        AssetDatabase.LoadAssetAtPath<GameObject>(result.LogicPath);
                    entry.FindPropertyRelative("editorAssetGuid").stringValue =
                        result.LogicGuid;
                    entry.FindPropertyRelative("clientViewAddress").stringValue =
                        result.Address;
                }
            }
            serialized.ApplyModifiedPropertiesWithoutUndo();
            table.ValidateOrThrow();
            EditorUtility.SetDirty(table);
        }

        private static void WriteMigrationReport(
            IReadOnlyList<UnitMigrationResult> results)
        {
            var builder = new StringBuilder();
            builder.AppendLine("# Unit prefab Addressables migration");
            builder.AppendLine();
            builder.AppendLine("| PrefabId | Legacy backup | Synchronous logic prefab | Local Addressable view | Address | Logic GUID | View GUID |");
            builder.AppendLine("|---:|---|---|---|---|---|---|");
            for (int i = 0; i < results.Count; i++)
            {
                UnitMigrationResult result = results[i];
                builder.AppendLine(
                    $"| {result.Spec.PrefabId} | `{result.ArchivePath}` | `{result.LogicPath}` | `{result.ViewPath}` | `{result.Address}` | `{result.LogicGuid}` | `{result.ViewGuid}` |");
            }
            builder.AppendLine();
            builder.AppendLine("The archive prefabs are not under `Resources`, are not Addressable, and exist only as a reversible migration reference. They must not be reachable from formal scenes/configuration or a player build.");
            Directory.CreateDirectory(Path.GetDirectoryName(MigrationReport));
            File.WriteAllText(
                MigrationReport,
                builder.ToString(),
                new UTF8Encoding(false));
            AssetDatabase.Refresh();
        }

        private static string ResolveExistingSourcePath(UnitMigrationSpec spec)
        {
            string[] candidates =
            {
                $"{LegacyRoot}/{spec.FileName}",
                $"{ArchiveRoot}/{spec.FileName}",
                $"{LogicRoot}/{spec.FileName}",
            };
            for (int i = 0; i < candidates.Length; i++)
                if (AssetDatabase.LoadAssetAtPath<GameObject>(candidates[i]) != null)
                    return candidates[i];
            throw new InvalidOperationException(
                $"No source prefab exists for {spec.FileName}.");
        }

        private static string GetRelativePath(Transform root, Transform current)
        {
            if (root == current)
                return root.name;
            var names = new Stack<string>();
            Transform cursor = current;
            while (cursor != null && cursor != root)
            {
                names.Push(cursor.name);
                cursor = cursor.parent;
            }
            return $"{root.name}/{string.Join("/", names)}";
        }

        private static void RequireCopy(string source, string destination)
        {
            if (!AssetDatabase.CopyAsset(source, destination))
                throw new InvalidOperationException(
                    $"Could not copy '{source}' to '{destination}'.");
            AssetDatabase.ImportAsset(
                destination,
                ImportAssetOptions.ForceSynchronousImport);
        }

        private static void EnsureFolder(string path)
        {
            string[] parts = path.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                string next = $"{current}/{parts[i]}";
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }

        private readonly struct UnitMigrationSpec
        {
            public readonly int PrefabId;
            public readonly string FileName;

            public UnitMigrationSpec(int prefabId, string fileName)
            {
                PrefabId = prefabId;
                FileName = fileName;
            }
        }

        private readonly struct UnitMigrationResult
        {
            public readonly UnitMigrationSpec Spec;
            public readonly string ArchivePath;
            public readonly string LogicPath;
            public readonly string ViewPath;
            public readonly string Address;
            public readonly string LogicGuid;
            public readonly string ViewGuid;

            public UnitMigrationResult(
                UnitMigrationSpec spec,
                string archivePath,
                string logicPath,
                string viewPath,
                string address,
                string logicGuid,
                string viewGuid)
            {
                Spec = spec;
                ArchivePath = archivePath;
                LogicPath = logicPath;
                ViewPath = viewPath;
                Address = address;
                LogicGuid = logicGuid;
                ViewGuid = viewGuid;
            }
        }
    }
}
