using System;
using System.Collections.Generic;
using Unity.Mathematics.FixedPoint;
using UnityEngine;

namespace FrameSyncMoba.Unit
{
    [Serializable]
    public struct CrowdControlParamAuthoring
    {
        public string Key;
        public CrowdControlParamType Type;
        public bool Required;
    }

    /// <summary>
    /// Flat, serializable module authoring (CC v6.2 3.3). Each module
    /// interprets only the fields it needs; Bake compiles them into
    /// ControlModuleOps.
    /// </summary>
    [Serializable]
    public struct CrowdControlModuleAuthoring
    {
        public ushort ModuleId;
        public string ParamKey0;
        public string ParamKey1;
        public string ParamKey2;
        public string ParamKey3;
        public float StaticFp0;
        public float StaticFp1;
        public int StaticData;
    }

    /// <summary>
    /// Single static configuration for one control (CC v6.2 2.1). Inspector
    /// fields plus hidden baked runtime fields live in the same asset.
    /// </summary>
    [CreateAssetMenu(
        fileName = "CrowdControlDefinition",
        menuName = "MOBA/Crowd Control Definition")]
    public sealed class CrowdControlDefinition : ScriptableObject
    {
        [Header("Authoring")]
        [SerializeField] private int controlId;
        [SerializeField] private CrowdControlIntensity intensity;
        [SerializeField] private ulong tags;
        [SerializeField] private CrowdControlDurationRule durationRule;
        [SerializeField] private CrowdControlParamAuthoring[] parameterSchema;
        [SerializeField] private CrowdControlModuleAuthoring[] modules;

        [Header("Baked (generated by Bake)")]
        [HideInInspector] public CrowdControlParamLayoutEntry[] BakedParamLayout;
        [HideInInspector] public byte BakedRequiredMask;
        [HideInInspector] public int BakedParamTotalSize;
        [HideInInspector] public ControlModuleOp[] BakedOnAddOps;
        [HideInInspector] public ControlModuleOp[] BakedCollectOps;
        [HideInInspector] public ControlModuleOp[] BakedSignalOps;
        [HideInInspector] public ControlModuleOp[] BakedOnRemoveOps;
        [HideInInspector] public CrowdControlSignalMask BakedSignalMask;

        public CrowdControlId ControlId => new CrowdControlId(controlId);
        public CrowdControlIntensity Intensity => intensity;
        public CrowdControlTagMask Tags => new CrowdControlTagMask(tags);
        public CrowdControlDurationRule DurationRule => durationRule;

        public CrowdControlParamLayout ParamLayout =>
            new CrowdControlParamLayout
            {
                Entries = BakedParamLayout,
                RequiredMask = BakedRequiredMask,
                TotalSize = BakedParamTotalSize,
            };

        public bool IsBaked =>
            BakedParamLayout != null &&
            (BakedOnAddOps != null ||
             BakedCollectOps != null ||
             BakedSignalOps != null ||
             BakedOnRemoveOps != null);

        public bool IsValid =>
            ControlId.IsValid &&
            intensity >= CrowdControlIntensity.Low &&
            intensity <= CrowdControlIntensity.High &&
            durationRule >= CrowdControlDurationRule.DefaultTenacity &&
            durationRule <= CrowdControlDurationRule.IgnoreTenacity &&
            IsBaked;

        /// <summary>
        /// Configure authoring fields and Bake in one call. Used by tests and
        /// by data-driven composition; editor assets use the same path.
        /// </summary>
        public void Configure(
            CrowdControlId id,
            CrowdControlIntensity configuredIntensity,
            ulong configuredTags,
            CrowdControlDurationRule rule,
            CrowdControlParamAuthoring[] schema,
            CrowdControlModuleAuthoring[] authoredModules)
        {
            controlId = id.Value;
            intensity = configuredIntensity;
            tags = configuredTags;
            durationRule = rule;
            parameterSchema = schema;
            modules = authoredModules;
            Bake();
        }

        /// <summary>
        /// Editor/test Bake (CC v6.2 2.6). Compiles authoring fields into the
        /// hidden runtime fields. Throws on invalid configuration.
        /// </summary>
        public void Bake()
        {
            if (controlId <= 0)
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': ControlId must be positive.");
            }
            if (intensity < CrowdControlIntensity.Low ||
                intensity > CrowdControlIntensity.High)
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': Intensity must be Low/Medium/High.");
            }
            if ((tags & ControlTagBits.Control) == 0UL)
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': every control requires the Control base tag.");
            }

            BakeParams();
            BakeModules();
        }

        /// <summary>Tag bits used by Bake validation (CC v6.2 5.3/5.5).</summary>
        public static class ControlTagBits
        {
            public const ulong Control = 1UL << 0;
            public const ulong Slow = 1UL << 1;
            public const ulong Root = 1UL << 2;
            public const ulong Silence = 1UL << 3;
            public const ulong Blind = 1UL << 4;
            public const ulong Disarm = 1UL << 5;
            public const ulong ForcedBehavior = 1UL << 6;
            public const ulong ForcedMove = 1UL << 7;
            public const ulong Displacement = 1UL << 8;
            public const ulong Airborne = 1UL << 9;
            public const ulong Grounded = 1UL << 10;
            public const ulong Nearsight = 1UL << 11;
            public const ulong Sleep = 1UL << 12;
            public const ulong Suppression = 1UL << 13;
            public const ulong Polymorph = 1UL << 14;
            public const ulong Cripple = 1UL << 15;
            public const ulong Taunt = 1UL << 16;
            public const ulong Charm = 1UL << 17;
            public const ulong Fear = 1UL << 18;
            public const ulong Drowsy = 1UL << 19;
        }

        private void BakeParams()
        {
            var entries =
                new List<CrowdControlParamLayoutEntry>();
            byte requiredMask = 0;
            int cursor = 0;
            CrowdControlParamAuthoring[] schema =
                parameterSchema;
            if (schema != null)
            {
                for (int i = 0;
                     i < schema.Length;
                     i++)
                {
                    CrowdControlParamAuthoring item =
                        schema[i];
                    if (string.IsNullOrWhiteSpace(item.Key))
                    {
                        throw new InvalidOperationException(
                            $"CrowdControlDefinition '{name}': param {i} has no Key.");
                    }
                    if (!ControlParamKeys.TryGetByName(
                            item.Key,
                            out CrowdControlParamKey key))
                    {
                        throw new InvalidOperationException(
                            $"CrowdControlDefinition '{name}': unknown param key '{item.Key}'.");
                    }
                    int size = CrowdControlParamTypes.GetSize(item.Type);
                    int alignment = CrowdControlParamTypes.GetAlignment(item.Type);
                    if (size == 0)
                    {
                        throw new InvalidOperationException(
                            $"CrowdControlDefinition '{name}': param '{item.Key}' has unsupported type {item.Type}.");
                    }
                    cursor = Align(cursor, alignment);
                    entries.Add(
                        new CrowdControlParamLayoutEntry
                        {
                            Key = key,
                            Type = item.Type,
                            Offset = cursor,
                            Size = size,
                        });
                    if (item.Required)
                    {
                        if (i >= 8)
                        {
                            throw new InvalidOperationException(
                                $"CrowdControlDefinition '{name}': more than 8 required params.");
                        }
                        requiredMask |= (byte)(1 << i);
                    }
                    cursor += size;
                    if (cursor > 64)
                    {
                        throw new InvalidOperationException(
                            $"CrowdControlDefinition '{name}': param layout exceeds 64 bytes.");
                    }
                }
            }
            BakedParamLayout = entries.ToArray();
            BakedRequiredMask = requiredMask;
            BakedParamTotalSize = cursor;
        }

        private void BakeModules()
        {
            var onAdd = new List<ControlModuleOp>();
            var collect = new List<ControlModuleOp>();
            var signal = new List<ControlModuleOp>();
            var onRemove = new List<ControlModuleOp>();
            CrowdControlSignalMask signalMask =
                CrowdControlSignalMask.None;
            bool hasForcedMoveOnAdd = false;

            CrowdControlModuleAuthoring[] authoring =
                modules;
            if (authoring != null)
            {
                for (int i = 0;
                     i < authoring.Length;
                     i++)
                {
                    CrowdControlModuleAuthoring item =
                        authoring[i];
                    ControlModuleOp op =
                        CompileModule(item);
                    switch (op.Hook)
                    {
                        case ControlModuleHook.OnAdd:
                            onAdd.Add(op);
                            if (item.ModuleId ==
                                CrowdControlModuleId.ForcedMoveOnAdd)
                            {
                                hasForcedMoveOnAdd = true;
                            }
                            break;
                        case ControlModuleHook.Collect:
                            collect.Add(op);
                            break;
                        case ControlModuleHook.OnSignal:
                            signal.Add(op);
                            signalMask |=
                                (CrowdControlSignalMask)op.StaticData;
                            break;
                        case ControlModuleHook.OnRemove:
                            onRemove.Add(op);
                            break;
                    }
                }
            }

            if ((tags & ControlTagBits.ForcedMove) != 0UL)
            {
                if (!hasForcedMoveOnAdd)
                {
                    throw new InvalidOperationException(
                        $"CrowdControlDefinition '{name}': ForcedMove tag requires a ForcedMoveOnAdd module.");
                }
                ValidateForcedMoveParams();
            }

            BakedOnAddOps = onAdd.ToArray();
            BakedCollectOps = collect.ToArray();
            BakedSignalOps = signal.ToArray();
            BakedOnRemoveOps = onRemove.ToArray();
            BakedSignalMask = signalMask;
        }

        private ControlModuleOp CompileModule(
            in CrowdControlModuleAuthoring item)
        {
            int executorIndex = item.ModuleId;
            if (executorIndex <= 0 ||
                executorIndex >= CrowdControlModuleId.Count)
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': unknown module id {item.ModuleId}.");
            }

            var op = new ControlModuleOp
            {
                ExecutorIndex = executorIndex,
                StaticData = item.StaticData,
                StaticFp0 = (fp)item.StaticFp0,
                StaticFp1 = (fp)item.StaticFp1,
                ParamOffset0 = ResolveParamOffset(item.ParamKey0),
                ParamOffset1 = ResolveParamOffset(item.ParamKey1),
                ParamOffset2 = ResolveParamOffset(item.ParamKey2),
                ParamOffset3 = ResolveParamOffset(item.ParamKey3),
            };

            switch (item.ModuleId)
            {
                case CrowdControlModuleId.BlockActions:
                    op.Hook = ControlModuleHook.Collect;
                    break;
                case CrowdControlModuleId.MaxMoveSlow:
                case CrowdControlModuleId.MaxAttackSpeedSlow:
                case CrowdControlModuleId.MinVisionScale:
                    op.Hook = ControlModuleHook.Collect;
                    RequireParam(op, item.ParamKey0);
                    break;
                case CrowdControlModuleId.BasicAttackMiss:
                    op.Hook = ControlModuleHook.Collect;
                    break;
                case CrowdControlModuleId.ForcedBehavior:
                    op.Hook = ControlModuleHook.Collect;
                    RequireParam(op, item.ParamKey0);
                    RequireParam(op, item.ParamKey1);
                    break;
                case CrowdControlModuleId.ForcedMoveOnAdd:
                    op.Hook = ControlModuleHook.OnAdd;
                    RequireParam(op, item.ParamKey0);
                    RequireParam(op, item.ParamKey1);
                    RequireParam(op, item.ParamKey2);
                    break;
                case CrowdControlModuleId.RemoveOnSignal:
                    op.Hook = ControlModuleHook.OnSignal;
                    if (item.StaticData <= 0)
                    {
                        throw new InvalidOperationException(
                            $"CrowdControlDefinition '{name}': RemoveOnSignal requires a signal bit mask in StaticData.");
                    }
                    break;
                case CrowdControlModuleId.AddControlOnNaturalExpire:
                    op.Hook = ControlModuleHook.OnRemove;
                    if (item.StaticData <= 0)
                    {
                        throw new InvalidOperationException(
                            $"CrowdControlDefinition '{name}': AddControlOnNaturalExpire requires a target ControlId in StaticData.");
                    }
                    RequireParam(op, item.ParamKey0);
                    ValidateParamType(
                        item.ParamKey0,
                        CrowdControlParamType.Int,
                        "AddControlOnNaturalExpire duration");
                    break;
                default:
                    throw new InvalidOperationException(
                        $"CrowdControlDefinition '{name}': module {item.ModuleId} has no bake rule.");
            }
            return op;
        }

        private int ResolveParamOffset(string key)
        {
            if (string.IsNullOrWhiteSpace(key))
            {
                return -1;
            }
            if (!ControlParamKeys.TryGetByName(
                    key,
                    out CrowdControlParamKey paramKey))
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': unknown param key '{key}'.");
            }
            CrowdControlParamLayoutEntry[] layout =
                BakedParamLayout;
            for (int i = 0;
                 i < layout.Length;
                 i++)
            {
                if (layout[i].Key == paramKey)
                {
                    return layout[i].Offset;
                }
            }
            throw new InvalidOperationException(
                $"CrowdControlDefinition '{name}': module references '{key}' which is not declared in the parameter schema.");
        }

        private void RequireParam(
            in ControlModuleOp op,
            string key)
        {
            if (op.ParamOffset0 < 0 &&
                op.ParamOffset1 < 0 &&
                op.ParamOffset2 < 0 &&
                op.ParamOffset3 < 0)
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': module requires a parameter key '{key}'.");
            }
        }

        private void ValidateParamType(
            string key,
            CrowdControlParamType expected,
            string label)
        {
            if (string.IsNullOrWhiteSpace(key))
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': {label} requires a parameter key.");
            }
            if (!ControlParamKeys.TryGetByName(
                    key,
                    out CrowdControlParamKey paramKey))
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': {label} references unknown key '{key}'.");
            }
            CrowdControlParamLayoutEntry[] layout =
                BakedParamLayout;
            for (int i = 0;
                 i < layout.Length;
                 i++)
            {
                if (layout[i].Key == paramKey)
                {
                    if (layout[i].Type != expected)
                    {
                        throw new InvalidOperationException(
                            $"CrowdControlDefinition '{name}': {label} key '{key}' must be {expected}.");
                    }
                    return;
                }
            }
            throw new InvalidOperationException(
                $"CrowdControlDefinition '{name}': {label} key '{key}' is not declared in the parameter schema.");
        }

        private void ValidateForcedMoveParams()
        {
            if (BakedParamLayout == null)
            {
                return;
            }
            bool hasDirection = false;
            bool hasDistance = false;
            bool hasMoveTicks = false;
            bool hasPriority = false;
            for (int i = 0;
                 i < BakedParamLayout.Length;
                 i++)
            {
                CrowdControlParamLayoutEntry entry =
                    BakedParamLayout[i];
                if (entry.Key == ControlParamKeys.Direction)
                {
                    hasDirection =
                        entry.Type ==
                        CrowdControlParamType.Fp2;
                }
                else if (entry.Key ==
                         ControlParamKeys.Distance)
                {
                    hasDistance =
                        entry.Type ==
                        CrowdControlParamType.Fp;
                }
                else if (entry.Key ==
                         ControlParamKeys.MoveTicks)
                {
                    hasMoveTicks =
                        entry.Type ==
                        CrowdControlParamType.Int;
                }
                else if (entry.Key ==
                         ControlParamKeys.ForcedMovePriority)
                {
                    hasPriority =
                        entry.Type ==
                        CrowdControlParamType.Short;
                }
            }
            if (!hasDirection ||
                !hasDistance ||
                !hasMoveTicks ||
                !hasPriority)
            {
                throw new InvalidOperationException(
                    $"CrowdControlDefinition '{name}': ForcedMove requires Direction(fp2), Distance(fp), MoveTicks(int) and ForcedMovePriority(short) params.");
            }
        }

        private static int Align(int value, int alignment)
        {
            int remainder = value % alignment;
            return remainder == 0
                ? value
                : value + (alignment - remainder);
        }
    }
}
