using Unity.Mathematics.FixedPoint;

namespace FrameSyncMoba.Unit
{
    /// <summary>
    /// Unit Framework v27.3 §3.2 — the kind of action being requested.
    /// </summary>
    public enum ActionKind : byte
    {
        None = 0,
        Move = 1,
        Attack = 2,
        Cast = 3,
    }

    /// <summary>
    /// Unit Framework v27.3 §3.2 — base for action requests generated by
    /// the BehaviorPlanner and evaluated by the ActionArbiter.
    /// </summary>
    public abstract class ActionRequest
    {
        public ActionKind Kind { get; protected set; }
        protected ActionRequest(ActionKind kind)
        {
            Kind = kind;
        }
    }

    /// <summary>
    /// A movement request generated by the BehaviorPlanner, e.g. chase-for-attack
    /// or chase-for-cast.
    /// </summary>
    public sealed class MoveActionRequest : ActionRequest
    {
        /// <summary>Destination in world space.</summary>
        public fp2 TargetPosition;

        /// <summary>
        /// Optional: the unit being chased. Provides context for the movement
        /// system to update the target position continuously.
        /// </summary>
        public UnitUid ChaseTarget;

        /// <summary>Desired stop distance from the target.</summary>
        public fp StopRange;

        public MovePurpose Purpose;

        public MoveActionRequest(
            fp2 targetPosition,
            fp stopRange = default,
            MovePurpose purpose =
                MovePurpose.PointMove)
            : base(ActionKind.Move)
        {
            TargetPosition = targetPosition;
            StopRange = stopRange;
            Purpose = purpose;
        }

        public MoveActionRequest(
            UnitUid chaseTarget,
            fp stopRange,
            MovePurpose purpose =
                MovePurpose.ChaseForAttack)
            : base(ActionKind.Move)
        {
            ChaseTarget = chaseTarget;
            StopRange = stopRange;
            Purpose = purpose;
        }
    }

    /// <summary>
    /// An attack request generated by the BehaviorPlanner when the unit
    /// is in range of its attack target.
    /// </summary>
    public sealed class AttackActionRequest : ActionRequest
    {
        /// <summary>The target unit to attack.</summary>
        public UnitUid TargetUnit;

        public AttackActionRequest(UnitUid targetUnit)
            : base(ActionKind.Attack)
        {
            TargetUnit = targetUnit;
        }
    }

    /// <summary>
    /// A cast request generated by the BehaviorPlanner when the unit
    /// is in range to cast the intended ability.
    /// </summary>
    public sealed class CastActionRequest : ActionRequest
    {
        /// <summary>The ability definition ID to cast.</summary>
        public int AbilityId;

        public AbilitySignalVerb Verb;
        public AimSnapshot Aim;

        public CastActionRequest(
            int abilityId,
            AbilitySignalVerb verb,
            in AimSnapshot aim)
            : base(ActionKind.Cast)
        {
            AbilityId = abilityId;
            Verb = verb;
            Aim = aim;
        }
    }
}
